# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft_stock.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10raft_stock.proto\x12\nraft_stock\"[\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"1\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\"\xa0\x01\n\x0e\x45ntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12-\n\x07\x65ntries\x18\x05 \x01(\x0b\x32\x1c.raft_stock.StockTransaction\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\"\xe0\x01\n\x10StockTransaction\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07stockId\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x05\x12\x45\n\x0ftransactionType\x18\x05 \x01(\x0e\x32,.raft_stock.StockTransaction.TransactionType\x12\r\n\x05price\x18\x06 \x01(\x01\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\x12\x0e\n\x06userId\x18\x08 \x01(\t\"$\n\x0fTransactionType\x12\x07\n\x03\x42UY\x10\x00\x12\x08\n\x04SELL\x10\x01\"0\n\x0f\x45ntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\x99\x01\n\x0bRaftService\x12@\n\x0bRequestVote\x12\x17.raft_stock.VoteRequest\x1a\x18.raft_stock.VoteResponse\x12H\n\rAppendEntries\x12\x1a.raft_stock.EntriesRequest\x1a\x1b.raft_stock.EntriesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_stock_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOTEREQUEST']._serialized_start=32
  _globals['_VOTEREQUEST']._serialized_end=123
  _globals['_VOTERESPONSE']._serialized_start=125
  _globals['_VOTERESPONSE']._serialized_end=174
  _globals['_ENTRIESREQUEST']._serialized_start=177
  _globals['_ENTRIESREQUEST']._serialized_end=337
  _globals['_STOCKTRANSACTION']._serialized_start=340
  _globals['_STOCKTRANSACTION']._serialized_end=564
  _globals['_STOCKTRANSACTION_TRANSACTIONTYPE']._serialized_start=528
  _globals['_STOCKTRANSACTION_TRANSACTIONTYPE']._serialized_end=564
  _globals['_ENTRIESRESPONSE']._serialized_start=566
  _globals['_ENTRIESRESPONSE']._serialized_end=614
  _globals['_RAFTSERVICE']._serialized_start=617
  _globals['_RAFTSERVICE']._serialized_end=770
# @@protoc_insertion_point(module_scope)
